import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
export async function renderTrace(sourcePath: string, directory: string) {
  const frames = JSON.parse(await readFile(sourcePath, "utf8")) as Array<{ tick: number; values: Record<string, number> }>;
  if (!Array.isArray(frames) || frames.length > 6001 || frames.some(f => !Number.isInteger(f.tick) || !f.values || Object.values(f.values).some(v => !Number.isInteger(v) || v < 0 || v > 15))) throw new Error("Invalid recorded signal trace");
  const path = join(directory, "waveform.html"), data = JSON.stringify(frames).replace(/</g, "\\u003c");
  await writeFile(path, `<!doctype html><meta charset="utf-8"><title>MC Engineer · 信号波形</title><style>body{background:#111c27;color:#dfebf5;font:14px system-ui;margin:28px}canvas{display:block;background:#162432;max-width:100%}small{color:#9eb6c9}</style><h1>信号波形</h1><p>横轴：实际游戏 Tick　纵轴：红石强度 0–15</p><small>线段仅连接采样点，不推断未采样时刻的信号。</small><p id="value">移动鼠标读取采样值</p><canvas id="trace"></canvas><script>const frames=${data};const names=[...new Set(frames.flatMap(f=>Object.keys(f.values)))],c=document.getElementById('trace'),g=c.getContext('2d');c.width=1200;c.height=Math.max(140,names.length*100+35);const end=Math.max(1,...frames.map(f=>f.tick)),x=t=>240+t/end*920;g.font='13px system-ui';names.forEach((name,i)=>{const base=80+i*100;g.fillStyle='#c0d3e3';g.fillText(name,12,base-25);g.strokeStyle='#304656';g.beginPath();g.moveTo(240,base);g.lineTo(1160,base);g.stroke();g.strokeStyle='#6ee0bd';g.beginPath();let first=true;frames.forEach(f=>{if(f.values[name]===undefined)return;const px=x(f.tick),py=base-f.values[name]*3.8;if(first){g.moveTo(px,py);first=false}else g.lineTo(px,py)});g.stroke();frames.forEach(f=>{if(f.values[name]!==undefined){g.fillStyle='#a4f5df';g.fillRect(x(f.tick)-2,base-f.values[name]*3.8-2,4,4)}})});g.fillStyle='#c0d3e3';for(let t=0;t<=end;t+=Math.max(1,Math.ceil(end/12)))g.fillText(String(t),x(t),c.height-8);c.onmousemove=e=>{const tick=((e.clientX-c.getBoundingClientRect().left)*c.width/c.clientWidth-240)/920*end;const f=frames.reduce((a,b)=>!a||Math.abs(b.tick-tick)<Math.abs(a.tick-tick)?b:a,null);document.getElementById('value').textContent=f?'Tick '+f.tick+' · '+Object.entries(f.values).map(([k,v])=>k+' = '+v).join(' / '):'没有采样数据'};</script>`, "utf8");
  return { path, samples: frames.length, sourcePath };
}
