import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { WorkspaceStore } from "./workspace-store.js";
import { resolveWorkspace } from "./workspace-model.js";
import { readOptional, type BuildPlan } from "./workspace-plan.js";

export async function previewWorkspace(store: WorkspaceStore) {
  const head = await store.read(), model = resolveWorkspace(head.source);
  const baseline = await readOptional<{ revisionId: string }>(join(store.directory, "DEPLOYED.json"));
  const old = baseline ? resolveWorkspace((await store.revision(baseline.revisionId)).source) : undefined;
  const plan = await readOptional<BuildPlan>(join(store.directory, "deployment.json"));
  const limit = 12000, simplified = model.operations.length > limit;
  const operations = simplified ? model.modules.filter(m => m.bounds).map(m => ({ ...m.bounds!, block: m.kind, moduleId: m.id, stage: "bounds" })) : model.operations;
  const changed = new Set(model.source.modules.filter(m => JSON.stringify(m) !== JSON.stringify(old?.source.modules.find(o => o.id === m.id))
    || JSON.stringify(model.modules.find(o => o.id === m.id)) !== JSON.stringify(old?.modules.find(o => o.id === m.id))
    || (m.template && JSON.stringify(model.source.templates[m.template]) !== JSON.stringify(old?.source.templates[m.template]))).map(m => m.id));
  const data = { name: head.source.name, revision: head.revision, bounds: model.bounds, modules: model.modules, ports: model.ports,
    connections: model.connections, operations, simplified, changed: [...changed],
    removed: old?.modules.filter(m => !model.modules.some(n => n.id === m.id)) ?? [],
    plan: plan?.revisionId === head.id ? plan : undefined, history: await store.history(), sourcePath: join(store.directory, "revisions", `${head.id}.json`) };
  const path = join(store.directory, "workbench.html");
  await writeFile(path, page(JSON.stringify(data).replace(/</g, "\\u003c")), "utf8");
  return { path, revision: head.revision, simplified, operationCount: model.operations.length, snapshot: true };
}
function page(json: string) { return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>MC Engineer · 工程工作台</title><link rel="icon" href="data:,"><style>
*{box-sizing:border-box}body{margin:0;background:#10151c;color:#dfe8f0;font:14px system-ui,sans-serif}header{height:74px;padding:14px 24px;border-bottom:1px solid #34404d;display:flex;align-items:center;gap:22px}h1{font-size:21px;margin:0}small,.muted{color:#a6b4c5}main{display:grid;grid-template-columns:270px 1fr 300px;height:calc(100vh - 74px)}aside{padding:18px;overflow:auto;border-right:1px solid #34404d}section{position:relative;min-width:0}canvas{width:100%;height:100%;display:block;touch-action:none}button,input,select{background:#202e3c;color:#e1ecf4;border:1px solid #46576c;border-radius:5px;padding:7px}button{cursor:pointer}button:hover,button.selected{border-color:#61d7bc;background:#244841}.module{display:block;width:100%;text-align:left;margin-bottom:7px;padding:10px}.module small{display:block;margin-top:5px}.toolbar{position:absolute;top:15px;left:16px;right:16px;display:flex;align-items:center;gap:10px;flex-wrap:wrap;background:#10151ce6;padding:10px;border-radius:8px}label{display:flex;align-items:center;gap:6px}.hint{position:absolute;bottom:16px;left:20px;background:#10151ce6;padding:9px 12px;color:#b5c5d4;border-radius:6px}h2{font-size:13px;letter-spacing:1px;color:#86a4ba;margin-top:24px}p{line-height:1.65}.badge{color:#61d7bc;background:#15352f;padding:6px 9px;border-radius:5px}.row{padding:9px 0;border-bottom:1px solid #2a3643;overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;color:#b6cfdf}#details{border-left:1px solid #34404d;border-right:0}#error{color:#ff9b92}input[type=range]{width:135px} @media(max-width:1000px){main{grid-template-columns:220px 1fr}#details{display:none}}
</style><header><div><h1 id="title"></h1><small>MC ENGINEER / 工程快照</small></div><span class="badge" id="revision"></span><span class="muted">模块 · 施工阶段 · 信号端口</span></header><main><aside><input id="search" placeholder="查找模块…" style="width:100%"><h2>模块树</h2><button id="all" class="module selected">全部模块</button><div id="modules"></div><h2>版本记录</h2><div id="history"></div></aside><section><canvas id="view"></canvas><div class="toolbar"><button id="reset">复位视角</button><label>Y 切片 <input type="range" id="slice"><span id="level"></span></label><label><input type="checkbox" id="ports" checked>端口</label><label><input type="checkbox" id="changes">突出改动</label><label><input type="checkbox" id="isolate">只看所选</label></div><div class="hint">拖动旋转 · 滚轮缩放 · 选择左侧模块定位 · 几何示意，不模拟红石</div></section><aside id="details"><h2>工程状态</h2><div id="summary"></div><h2>所选模块</h2><div id="selection">选择模块查看范围和端口</div><h2>连接契约</h2><div id="connections"></div><h2>说明</h2><p class="muted">这是生成时的离线快照。用工程工具修改源文件、规划部署或运行测试后重新生成。连接声明不代表物理线路已连接。</p><p id="error"></p></aside></main>
<script>const d=${json};const $=id=>document.getElementById(id);$('title').textContent=d.name;$('revision').textContent='r'+d.revision;
const c=$('view'),ctx=c.getContext('2d');let selected='',yaw=-.65,zoom=1,drag;const b=d.bounds||{from:{x:0,y:0,z:0},to:{x:16,y:16,z:16}};let center={x:(b.from.x+b.to.x)/2,y:(b.from.y+b.to.y)/2,z:(b.from.z+b.to.z)/2};
const span=Math.max(12,b.to.x-b.from.x+1,b.to.z-b.from.z+1,b.to.y-b.from.y+1);$('slice').min=b.from.y;$('slice').max=b.to.y;$('slice').value=b.to.y;
function node(tag,text,parent,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;parent.append(n);return n}
const moduleById=new Map(d.modules.map(m=>[m.id,m])),children=new Map(),expanded=new Set();for(const m of d.modules){const parent=m.parent||'';if(!children.has(parent))children.set(parent,[]);children.get(parent).push(m)}
function renderModules(){const query=$('search').value.toLowerCase(),cache=new Map();function matches(m){if(cache.has(m.id))return cache.get(m.id);const yes=!query||(m.id+' '+m.name+' '+m.kind).toLowerCase().includes(query)||(children.get(m.id)||[]).some(matches);cache.set(m.id,yes);return yes}function walk(parent,depth){for(const m of children.get(parent)||[]){if(!matches(m))continue;const branch=children.has(m.id),n=node('button',(branch?(expanded.has(m.id)||query?'▾ ':'▸ '):'')+m.name,$('modules'),'module');n.dataset.id=m.id;n.style.paddingLeft=(10+depth*12)+'px';n.classList.toggle('selected',m.id===selected);node('small',m.id+' · '+m.kind,n);n.onclick=()=>{select(m.id);if(branch){expanded.has(m.id)?expanded.delete(m.id):expanded.add(m.id);renderModules()}};if(branch&&(query||expanded.has(m.id)))walk(m.id,depth+1)}}$('modules').replaceChildren();walk('',0)}
function belongs(id){if(!selected)return true;while(id){if(id===selected)return true;id=moduleById.get(id)?.parent}return false}function select(id){selected=id;document.querySelectorAll('.module').forEach(n=>n.classList.toggle('selected',n.dataset.id===id||(!id&&n.id==='all')));$('selection').replaceChildren();const m=moduleById.get(id),members=d.modules.filter(m=>belongs(m.id)),boxes=members.filter(m=>m.bounds).map(m=>m.bounds),bounds=boxes.length?{from:Object.fromEntries(['x','y','z'].map(a=>[a,Math.min(...boxes.map(b=>b.from[a]))])),to:Object.fromEntries(['x','y','z'].map(a=>[a,Math.max(...boxes.map(b=>b.to[a]))]))}:undefined;if(m){node('strong',m.name,$('selection'));node('pre',JSON.stringify({id:m.id,parent:m.parent,bounds,modules:members.length,rotation:m.rotation},null,2),$('selection'));const ports=d.ports.filter(p=>belongs(p.moduleId));for(const p of ports.slice(0,48))node('div',p.ref+' · '+p.kind+' · '+p.positions.length+' bit · '+p.sample,$('selection'),'row');if(ports.length>48)node('p','共 '+ports.length+' 个端口；选择子模块查看其余端口。',$('selection'),'muted');}if(bounds)center=Object.fromEntries(['x','y','z'].map(a=>[a,(bounds.from[a]+bounds.to[a])/2]));draw()}
$('all').onclick=()=>select('');$('search').oninput=renderModules;renderModules();
for(const h of d.history)node('div','r'+h.revision+' · '+h.message,$('history'),'row');for(const l of d.connections)node('div',l.from+' → '+l.to+' / '+l.width+' bit',$('connections'),'row');if(!d.connections.length)node('p','尚无连接声明',$('connections'),'muted');
node('p',d.modules.length+' 个模块 · '+d.ports.length+' 个端口',$('summary'));if(d.plan){node('div',d.plan.status,$('summary'),'badge');node('pre',JSON.stringify(d.plan.diff,null,2),$('summary'));node('p','阶段：'+d.plan.stages.map(s=>s.name).join(' → '),$('summary'))}else node('p','尚无匹配本版本的施工计划',$('summary'),'muted');
if(d.simplified)$('error').textContent='操作超过 12,000 个，当前仅展示模块包围盒。';
function color(id){let h=0;for(const v of id)h=(h*31+v.charCodeAt(0))|0;return 'hsl('+((h>>>0)%360)+' 38% 52%)'}
function project(x,y,z){x-=center.x;y-=center.y;z-=center.z;const u=x*Math.cos(yaw)-z*Math.sin(yaw),v=x*Math.sin(yaw)+z*Math.cos(yaw);const scale=Math.min(c.clientWidth,c.clientHeight)*.63/span*zoom;return [c.clientWidth/2+u*scale,c.clientHeight/2+(v*.46-y*.88)*scale,v+y*.05]}
function draw(){const ratio=devicePixelRatio||1;c.width=c.clientWidth*ratio;c.height=c.clientHeight*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.fillStyle='#101923';ctx.fillRect(0,0,c.clientWidth,c.clientHeight);const cut=+$('slice').value;$('level').textContent=cut;const polys=[];
function box(o,removed){if(o.from.y>cut||($('isolate').checked&&selected&&!belongs(o.moduleId)))return;const a=o.from,t={...o.to,y:Math.min(o.to.y,cut)},v=[[a.x,a.y,a.z],[t.x+1,a.y,a.z],[t.x+1,a.y,t.z+1],[a.x,a.y,t.z+1],[a.x,t.y+1,a.z],[t.x+1,t.y+1,a.z],[t.x+1,t.y+1,t.z+1],[a.x,t.y+1,t.z+1]].map(p=>project(...p));const fill=removed?'#e87578':$('changes').checked?(d.changed.includes(o.moduleId)?'#e2bd6b':'#476177'):color(o.moduleId);for(const face of [[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7],[4,5,6,7]])polys.push({v:face.map(i=>v[i]),depth:face.reduce((s,i)=>s+v[i][2],0)/4,fill,alpha:selected&&!belongs(o.moduleId) ? .16 : removed ? .3 : .85,selected:o.moduleId===selected})}
for(const o of d.operations)if(o.block!=='minecraft:air')box(o,false);if($('changes').checked)for(const m of d.removed)if(m.bounds)box({...m.bounds,moduleId:m.id},true);
polys.sort((a,b)=>a.depth-b.depth);for(const p of polys){ctx.globalAlpha=p.alpha;ctx.beginPath();p.v.forEach((v,i)=>i?ctx.lineTo(v[0],v[1]):ctx.moveTo(v[0],v[1]));ctx.closePath();ctx.fillStyle=p.fill;ctx.fill();ctx.strokeStyle=p.selected?'#bcffed':'#10232b';ctx.lineWidth=p.selected?1.2:.45;ctx.stroke()}ctx.globalAlpha=1;
if($('ports').checked)for(const p of d.ports){if(selected&&!belongs(p.moduleId))continue;p.positions.forEach((pos,i)=>{if(pos.y>cut)return;const v=project(pos.x+.5,pos.y+.8,pos.z+.5);ctx.fillStyle=p.kind==='input'?'#f3b873':'#72ead4';ctx.beginPath();ctx.arc(v[0],v[1],4,0,Math.PI*2);ctx.fill();if(i===0){ctx.font='12px system-ui';ctx.fillText(p.ref,v[0]+7,v[1]-6)}})}ctx.fillStyle='#9bafc2';ctx.font='12px system-ui';ctx.fillText('X / Z 旋转 '+Math.round(yaw*180/Math.PI)+'°',20,c.clientHeight-70)}
c.onpointerdown=e=>{drag=e.clientX;c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(drag!==undefined){yaw+=(e.clientX-drag)*.009;drag=e.clientX;draw()}};c.onpointerup=()=>drag=undefined;c.onwheel=e=>{e.preventDefault();zoom=Math.max(.08,Math.min(70,zoom*Math.exp(-e.deltaY*.001)));draw()};$('reset').onclick=()=>{yaw=-.65;zoom=1;center={x:(b.from.x+b.to.x)/2,y:(b.from.y+b.to.y)/2,z:(b.from.z+b.to.z)/2};draw()};for(const id of ['slice','ports','changes','isolate'])$(id).oninput=draw;new ResizeObserver(draw).observe(c);draw();</script></html>`; }
